INSERT INTO PUBLIC.USERS (NAME) VALUES ('Teet Järveküla');
INSERT INTO PUBLIC.USERS (NAME) VALUES ('Denizhan Aras');
INSERT INTO PUBLIC.USERS (NAME) VALUES ('Just Another Test User');

INSERT INTO PUBLIC.CARS (MAKE, MODEL, NUMBER_PLATE, USER_ID) VALUES ('Lada', '2101', '123ASD', 1);
INSERT INTO PUBLIC.CARS (MAKE, MODEL, NUMBER_PLATE, USER_ID) VALUES ('Kia', 'Sorento', '534TTT', 1);
INSERT INTO PUBLIC.CARS (MAKE, MODEL, NUMBER_PLATE, USER_ID) VALUES ('Mercedes', 'CLA 180', '666TST', 2);
INSERT INTO PUBLIC.CARS (MAKE, MODEL, NUMBER_PLATE, USER_ID) VALUES ('Kia', 'Sportage', '890UYN', 3);
INSERT INTO PUBLIC.CARS (MAKE, MODEL, NUMBER_PLATE, USER_ID) VALUES ('Renault', 'Talisman', '376FBS', 3);
INSERT INTO PUBLIC.CARS (MAKE, MODEL, NUMBER_PLATE, USER_ID) VALUES ('Peugeot', 'E-2008', '249DNA', 3);



